### ISSUE TITLE
Heatmap: add tooltip to explain "ad hoc" results.

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#997]

**Comment by tfrcarvalho** [comment]
Seem to be called "ad hoc" now.
After discussion with @boris-dimitrov, decided not hide these but instead provide a tooltip with an explanation of what it means.

Boris, can you provide a explanation and a condition of how to identify these cases?

**Comment by boris-dimitrov** [comment]
Tooltip:   'Due to a data import issue, the various species of this genus cannot be grouped together at the genus level.  While we work to fix this bug, each affected species will appear by itself in a separate "ad hoc genus" bucket.  The species level counts are still correct, and other genera are unaffected.'

My personal advice:   Do not bother trying to explain to the user in detail what each of our bugs could mean.   Just make sure the bug is reported so we can fix it.

**Comment by boris-dimitrov** [comment]
In report_helper.rb, search for "Ad hoc bucket" and note the comment on the function where that appears, and then the function that calls that function.  You will see that such occurrences are aggreagated and logged as a warning:
```
Rails.logger.warn "Missing taxon_counts for genus ids #{missing_genera.to_a} corresponding to taxon ids #{taxids_with_missing_genera.to_a}." unless missing_genera.empty?
```
That would be the appropriate place raise an airbrake alert.
